/*
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl.validation

import org.eclipse.xtext.util.Strings
import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.ValidationMessageAcceptor
import org.xtext.example.mydsl.myDsl.Entity
import org.xtext.example.mydsl.myDsl.Feature
import org.xtext.example.mydsl.myDsl.MyDslPackage
import org.xtext.example.mydsl.myDsl.PackageDeclaration

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
	@Check def void checkTypeNameStartsWithCapital(Entity entity) {
		if (!Character::isUpperCase(entity.getName().charAt(0))) {
			warning("Name should start with a capital", MyDslPackage.Literals::ABSTRACT_ELEMENT__NAME,
				ValidationMessageAcceptor::INSIGNIFICANT_INDEX, IssueCodes::INVALID_TYPE_NAME, entity.getName())
		}
	}

	@Check def void checkFeatureNameStartsWithLowercase(Feature feature) {
		if (!Character::isLowerCase(feature.getName().charAt(0))) {
			warning("Name should start with a lowercase", MyDslPackage.Literals::FEATURE__NAME,
				ValidationMessageAcceptor::INSIGNIFICANT_INDEX, IssueCodes::INVALID_FEATURE_NAME, feature.getName())
		}
	}

	@Check def void checkPackage(PackageDeclaration packages) {
		if (Strings::isEmpty(packages.getName())) {
			error("Name cannot be empty", MyDslPackage.Literals::ABSTRACT_ELEMENT__NAME)
		}
		if (packages.getName().equals("java")) {
			error("Invalid package name", MyDslPackage.Literals::ABSTRACT_ELEMENT__NAME)
		}
}
	
}
